name: Generate and Deploy Member Pages

on:
  push:
    paths:
      - '_data/*.yml'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Specify the version of Ruby you need
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Generate member pages
        run: python generate_members.py

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

